name: Scheduler - Full Football Scraper

on:
  schedule:
    - cron: '0 2 * * *' # This runs at 4 AM every day (Spanish time)
  workflow_dispatch: # Allows manual triggering

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    outputs:
      python-path: ${{ steps.python-setup.outputs.python-path }}

  scrape_futbolfantasy:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run FutbolFantasy Scraper
        run: python ./scraping_tasks/scrape_futbolfantasy.py

  scrape_futmondo:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Futmondo Scraper
        run: python ./scraping_tasks/scrape_futmondo.py

  scrape_transfermarket_penalties:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run TransferMarket Penalties Scraper
        run: python ./scraping_tasks/scrape_transfermarket_penalties.py

  scrape_transfermarket_teamhistory:
    needs: install-dependencies
    if: github.event_name == 'schedule' && (github.event.schedule == '0 2 * * 2') && contains('8 9 1 2', github.event.schedule_month)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run TransferMarket Team History Scraper
        run: python ./scraping_tasks/scrape_transfermarket_teamhistory.py

  scrape_sofascore:
    needs: install-dependencies
    if: github.event_name == 'schedule' && github.event.schedule == '0 2 * * 2'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SofaScore Scraper
        run: python ./scraping_tasks/scrape_sofascore.py

  commit-and-push:
    needs: [scrape_futbolfantasy, scrape_futmondo, scrape_transfermarket_penalties, scrape_transfermarket_teamhistory, scrape_sofascore]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated commit by GitHub Action"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
