name: Scheduler - Full Football Scraper

on:
  schedule:
    - cron: '0 2 * * 0,1,3,4,5,6'  # Every day at 4 AM (Spanish time) except Tuesdays
    - cron: '0 2 * 1,2,8,9 2'      # Every Tuesday at 4 AM (Spanish time) in Jan, Feb, Aug, Sep
    - cron: '0 2 * 3,4,5,6,7,10,11,12 2'          # Every Tuesday at 4 AM (Spanish time) except Jan, Feb, Aug, Sep
#    - cron: '0 2 * * *' # This runs at 4 AM every day (Spanish time)
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape_biwenger:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set the job timeout to 10 minutes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Biwenger Scraper
        run: python ./scraping_tasks/scrape_biwenger.py

      - name: Upload Biwenger DATA files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: biwenger-data
          path: |
            csv_files/*biwenger*.csv
            json_files/*biwenger*.json

  scrape_elo_ratings:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set the job timeout to 10 minutes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Elo Ratings Scraper
        run: python ./scraping_tasks/scrape_elo_ratings.py

      - name: Upload Elo Ratings DATA files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: elo-ratings-data
          path: |
            csv_files/*elo*ratings*.csv
            json_files/*elo*ratings*.json

  scrape_futmondo:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set the job timeout to 30 minutes
    if: (github.event_name == 'workflow_dispatch') || (github.event.schedule == '0 2 * 1,2,8,9 2')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Futmondo Scraper
        run: python ./scraping_tasks/scrape_futmondo.py

      - name: Upload Futmondo DATA files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: futmondo-data
          path: |
            csv_files/*futmondo*.csv
            json_files/*futmondo*.json

  scrape_transfermarket_penalty_takers:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set the job timeout to 30 minutes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TransferMarket Penalty Takers Scraper
        run: python ./scraping_tasks/scrape_transfermarket_penalty_takers.py

      - name: Upload TransferMarket Penalty Takers DATA files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: transfermarket-penalty-takers-data
          path: |
            csv_files/*transfermarket*penalt*taker*.csv
            json_files/*transfermarket*penalt*taker*.json

  scrape_transfermarket_penalty_savers:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set the job timeout to 30 minutes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TransferMarket Penalty Savers Scraper
        run: python ./scraping_tasks/scrape_transfermarket_penalty_savers.py

      - name: Upload TransferMarket Penalty Savers DATA files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: transfermarket-penalty-savers-data
          path: |
            csv_files/*transfermarket*penalt*saver*.csv
            json_files/*transfermarket*penalt*saver*.json

  scrape_transfermarket_teamhistory:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Set the job timeout to 120 minutes
#    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule' && github.event.schedule_weekday == '2' && (github.event.schedule_month == '8' || github.event.schedule_month == '9' || github.event.schedule_month == '1' || github.event.schedule_month == '2'))
    if: (github.event_name == 'workflow_dispatch') || (github.event.schedule == '0 2 * 1,2,8,9 2')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TransferMarket Team History Scraper
        run: python ./scraping_tasks/scrape_transfermarket_teamhistory.py

      - name: Upload TransferMarket Team History DATA files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: transfermarket-teamhistory-data
          path: |
            csv_files/*transfermarket*history*.csv
            json_files/*transfermarket*history*.json

  commit-and-push:
    needs: [scrape_biwenger, scrape_elo_ratings, scrape_futmondo, scrape_transfermarket_penalty_takers, scrape_transfermarket_penalty_savers, scrape_transfermarket_teamhistory]
    if: ${{ always() && (
          (needs.scrape_biwenger.result == 'success' || needs.scrape_biwenger.result == 'skipped' || needs.scrape_biwenger.result == 'cancelled' || needs.scrape_biwenger.result == 'failure') &&
          (needs.scrape_elo_ratings.result == 'success' || needs.scrape_elo_ratings.result == 'skipped' || needs.scrape_elo_ratings.result == 'cancelled' || needs.scrape_elo_ratings.result == 'failure') &&
          (needs.scrape_futmondo.result == 'success' || needs.scrape_futmondo.result == 'skipped' || needs.scrape_futmondo.result == 'cancelled' || needs.scrape_futmondo.result == 'failure') &&
          (needs.scrape_transfermarket_penalty_takers.result == 'success' || needs.scrape_transfermarket_penalty_takers.result == 'skipped' || needs.scrape_transfermarket_penalty_takers.result == 'cancelled' || needs.scrape_transfermarket_penalty_takers.result == 'failure') &&
          (needs.scrape_transfermarket_penalty_savers.result == 'success' || needs.scrape_transfermarket_penalty_savers.result == 'skipped' || needs.scrape_transfermarket_penalty_savers.result == 'cancelled' || needs.scrape_transfermarket_penalty_savers.result == 'failure') &&
          (needs.scrape_transfermarket_teamhistory.result == 'success' || needs.scrape_transfermarket_teamhistory.result == 'skipped' || needs.scrape_transfermarket_teamhistory.result == 'cancelled' || needs.scrape_transfermarket_teamhistory.result == 'failure')
        )}}
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set the job timeout to 30 minutes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Biwenger DATA artifact
        if: needs.scrape_biwenger.result == 'success'
        uses: actions/download-artifact@v4
        with:
          name: biwenger-data
          -path: data_files/biwenger/

      - name: Move Biwenger DATA files to root csv_files and json_files directories
        if: needs.scrape_biwenger.result == 'success'
        run: |
          mv -f data_files/biwenger/*.csv csv_files/ 2>/dev/null || true
          mv -f data_files/biwenger/*.json json_files/ 2>/dev/null || true
          rm -rf data_files/biwenger

      - name: Download Elo Ratings DATA artifact
        if: needs.scrape_elo_ratings.result == 'success'
        uses: actions/download-artifact@v4
        with:
          name: elo-ratings-data
          -path: data_files/elo_ratings/

      - name: Move Elo Ratings DATA files to root csv_files and json_files directories
        if: needs.scrape_elo_ratings.result == 'success'
        run: |
          mv -f data_files/elo_ratings/*.csv csv_files/ 2>/dev/null || true
          mv -f data_files/elo_ratings/*.json json_files/ 2>/dev/null || true
          rm -rf data_files/elo_ratings

      - name: Download Futmondo DATA artifact
        if: needs.scrape_futmondo.result == 'success'
        uses: actions/download-artifact@v4
        with:
          name: futmondo-data
          -path: data_files/futmondo/

      - name: Move Futmondo DATA files to root csv_files and json_files directories
        if: needs.scrape_futmondo.result == 'success'
        run: |
          mv -f data_files/futmondo/*.csv csv_files/ 2>/dev/null || true
          mv -f data_files/futmondo/*.json json_files/ 2>/dev/null || true
          rm -rf data_files/futmondo

      - name: Download TransferMarket Penalty Takers DATA artifact
        if: needs.scrape_transfermarket_penalty_takers.result == 'success'
        uses: actions/download-artifact@v4
        with:
          name: transfermarket-penalty-takers-data
          -path: data_files/transfermarket_penalty_takers/

      - name: Move TransferMarket Penalty Takers DATA files to root csv_files and json_files directories
        if: needs.scrape_transfermarket_penalty_takers.result == 'success'
        run: |
          mv -f data_files/transfermarket_penalty_takers/*.csv csv_files/ 2>/dev/null || true
          mv -f data_files/transfermarket_penalty_takers/*.json json_files/ 2>/dev/null || true
          rm -rf data_files/transfermarket_penalty_takers

      - name: Download TransferMarket Penalty Savers DATA artifact
        if: needs.scrape_transfermarket_penalty_savers.result == 'success'
        uses: actions/download-artifact@v4
        with:
          name: transfermarket-penalty-savers-data
          -path: data_files/transfermarket_penalty_savers/

      - name: Move TransferMarket Penalty Savers DATA files to root csv_files and json_files directories
        if: needs.scrape_transfermarket_penalty_savers.result == 'success'
        run: |
          mv -f data_files/transfermarket_penalty_savers/*.csv csv_files/ 2>/dev/null || true
          mv -f data_files/transfermarket_penalty_savers/*.json json_files/ 2>/dev/null || true
          rm -rf data_files/transfermarket_penalty_savers

      - name: Download TransferMarket Team History DATA artifact
        if: needs.scrape_transfermarket_teamhistory.result == 'success'
        uses: actions/download-artifact@v4
        with:
          name: transfermarket-teamhistory-data
          -path: data_files/transfermarket_teamhistory/

      - name: Move TransferMarket Team History DATA files to root csv_files and json_files directories
        if: needs.scrape_transfermarket_teamhistory.result == 'success'
        run: |
          mv -f data_files/transfermarket_teamhistory/*.csv csv_files/ 2>/dev/null || true
          mv -f data_files/transfermarket_teamhistory/*.json json_files/ 2>/dev/null || true
          rm -rf data_files/transfermarket_teamhistory

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add csv_files/*.csv
          git add json_files/*.json
          git commit -m "Automated commit by GitHub Action"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
