name: Scheduler - Full Football Scraper

on:
  schedule:
    - cron: '0 2 * * *' # This runs at 4 AM every day (Spanish time)
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape_futbolfantasy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FutbolFantasy Scraper
        run: python ./scraping_tasks/scrape_futbolfantasy.py

      - name: Upload FutbolFantasy CSV files as artifact
        uses: actions/upload-artifact@v2
        with:
          name: futbolfantasy-csv
          path: csv_files/*futbolfantasy*.csv

  scrape_futmondo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Futmondo Scraper
        run: python ./scraping_tasks/scrape_futmondo.py

      - name: Upload Futmondo CSV files as artifact
        uses: actions/upload-artifact@v2
        with:
          name: futmondo-csv
          path: csv_files/*futmondo*.csv

  scrape_transfermarket_penalties:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TransferMarket Penalties Scraper
        run: python ./scraping_tasks/scrape_transfermarket_penalties.py

      - name: Upload TransferMarket Penalties CSV files as artifact
        uses: actions/upload-artifact@v2
        with:
          name: transfermarket-penalties-csv
          path: csv_files/*transfermarket*penalt*.csv

  scrape_transfermarket_teamhistory:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && (github.event.schedule == '0 2 * * 2') && contains('8 9 1 2', github.event.schedule_month)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TransferMarket Team History Scraper
        run: python ./scraping_tasks/scrape_transfermarket_teamhistory.py

      - name: Upload TransferMarket Team History CSV files as artifact
        uses: actions/upload-artifact@v2
        with:
          name: transfermarket-teamhistory-csv
          path: csv_files/*transfermarket*history*.csv

  scrape_sofascore:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 2 * * 2'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run SofaScore Scraper
        run: python ./scraping_tasks/scrape_sofascore.py

      - name: Upload SofaScore CSV files as artifact
        uses: actions/upload-artifact@v2
        with:
          name: sofascore-csv
          path: csv_files/*sofascore*.csv

  commit-and-push:
    needs: [scrape_futbolfantasy, scrape_futmondo, scrape_transfermarket_penalties, scrape_transfermarket_teamhistory, scrape_sofascore]
    if: ${{ always() && (
          (needs.scrape_futbolfantasy.result == 'success' || needs.scrape_futbolfantasy.result == 'skipped') &&
          (needs.scrape_futmondo.result == 'success' || needs.scrape_futmondo.result == 'skipped') &&
          (needs.scrape_transfermarket_penalties.result == 'success' || needs.scrape_transfermarket_penalties.result == 'skipped') &&
          (needs.scrape_transfermarket_teamhistory.result == 'success' || needs.scrape_transfermarket_teamhistory.result == 'skipped') &&
          (needs.scrape_sofascore.result == 'success' || needs.scrape_sofascore.result == 'skipped')
        )}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download FutbolFantasy CSV artifact
        if: needs.scrape_futbolfantasy.result == 'success'
        uses: actions/download-artifact@v2
        with:
          name: futbolfantasy-csv
          path: csv_files/futbolfantasy/

      - name: Move FutbolFantasy CSV files to root csv_files directory
        if: needs.scrape_futbolfantasy.result == 'success'
        run: |
          mv -f csv_files/futbolfantasy/*.csv csv_files/
          rm -rf csv_files/futbolfantasy

      - name: Download Futmondo CSV artifact
        if: needs.scrape_futmondo.result == 'success'
        uses: actions/download-artifact@v2
        with:
          name: futmondo-csv
          path: csv_files/futmondo/

      - name: Move Futmondo CSV files to root csv_files directory
        if: needs.scrape_futmondo.result == 'success'
        run: |
          mv -f csv_files/futmondo/*.csv csv_files/
          rm -rf csv_files/futmondo

      - name: Download TransferMarket Penalties CSV artifact
        if: needs.scrape_transfermarket_penalties.result == 'success'
        uses: actions/download-artifact@v2
        with:
          name: transfermarket-penalties-csv
          path: csv_files/transfermarket_penalties/

      - name: Move TransferMarket Penalties CSV files to root csv_files directory
        if: needs.scrape_transfermarket_penalties.result == 'success'
        run: |
          mv -f csv_files/transfermarket_penalties/*.csv csv_files/
          rm -rf csv_files/transfermarket_penalties

      - name: Download TransferMarket Team History CSV artifact
        if: needs.scrape_transfermarket_teamhistory.result == 'success'
        uses: actions/download-artifact@v2
        with:
          name: transfermarket-teamhistory-csv
          path: csv_files/transfermarket_teamhistory/

      - name: Move TransferMarket Team History CSV files to root csv_files directory
        if: needs.scrape_transfermarket_teamhistory.result == 'success'
        run: |
          mv -f csv_files/transfermarket_teamhistory/*.csv csv_files/
          rm -rf csv_files/transfermarket_teamhistory

      - name: Download SofaScore CSV artifact
        if: needs.scrape_sofascore.result == 'success'
        uses: actions/download-artifact@v2
        with:
          name: sofascore-csv
          path: csv_files/sofascore/

      - name: Move SofaScore CSV files to root csv_files directory
        if: needs.scrape_sofascore.result == 'success'
        run: |
          mv -f csv_files/sofascore/*.csv csv_files/
          rm -rf csv_files/sofascore

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add csv_files/*.csv
          git commit -m "Automated commit by GitHub Action"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
